#!/bin/bash

if [ $# -ne 3 ]; then
	echo
  echo "Slovak cadastral data unzip tool:"
  echo "Usage: kt-kn_unzipper <data_dir> <working dir> <arj password>"
	echo
    exit
fi

data_dir=$1
work_dir=$2
passwd=$3

if [ -d "$work_dir" ]; then
  echo "Cleaning working directory:"
  rm -rf $work_dir/dbf/*
  rm -rf $work_dir/vgi/*
  rm -rf $work_dir/unzipped/*
else
  echo "Creating working directory"
  mkdir -p $work_dir/dbf
  mkdir -p $work_dir/vgi
  mkdir -p $work_dir/unzipped
fi

echo "Unzipping cadastral data"
mkdir -p $work_dir/unzipped/spi
unzip -d $work_dir/unzipped/spi $data_dir/spi*

mkdir -p $work_dir/unzipped/sgi
unzip -d $work_dir/unzipped/sgi $data_dir/sgi*

echo "Unzipping SGI files"
files=$(ls $work_dir/unzipped/sgi)

cd $work_dir/unzipped/sgi
for item in $files; do
  unzip $item
  rm $item
done

echo "Unzipping SPI files"
files=$(ls $work_dir/unzipped/spi)

cd $work_dir/unzipped/spi
for item in $files; do
  unzip $item
  rm $item
done

echo "Unzipping ARJ files"
files=$(ls $work_dir/unzipped/spi)
cd $work_dir/unzipped/spi
for item in $files; do
  arj e -g$passwd $item
  rm $item
done

echo "Done."
echo "Copying files."
cd $work_dir/unzipped/sgi
find ./ -type f -iname *.vgi -exec mv -- {} $work_dir/vgi \;
mv $work_dir/unzipped/spi/* $work_dir/dbf

rm -rf $work_dir/unzipped
